services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=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
      - PIXELCUT_API_KEY=sk_a7a5356f51944974b3b3b4e39ec96b60
    volumes:
      - ./database.sqlite:/usr/src/app/database.sqlite
    restart: unless-stopped 
